site_name: Lenticular
theme:
  name: material
  logo: assets/face-in-clouds.png
markdown_extensions:
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format